'use client'
// import type { Metadata } from "next";
import { Geist, Azeret_Mono as Geist_Mono } from 'next/font/google';
import "./globals.css";
import { AudioButton } from "@/components/audio-button";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Link from 'next/link';
import { MessageCircle } from 'lucide-react';
import { usePathname } from 'next/navigation';
import dynamic from 'next/dynamic';
import { ROUTES } from '@/lib/routes';
import ScrollProgress from '@/components/ScrollProgress';

const DynamicVantaBackground = dynamic(() => import('@/components/VantageBackground'), {
  ssr: false
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const isHomePage = pathname === ROUTES.HOME

  return (
    <html lang="en">
      <head>
      </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ScrollProgress />
          <DynamicVantaBackground>
            {isHomePage ? (
              <>
                <Navbar />
                <AudioButton />
                {children}
                <Link 
                  href={ROUTES.CHAT} 
                  className="fixed bottom-4 right-4 p-2 bg-white rounded-full shadow-lg hover:bg-gray-200 transition-colors duration-200"
                  aria-label="Go to Chatroom"
                >
                  <MessageCircle className="w-6 h-6 text-black" />
                </Link>
              </>
            ) : (
              <>
                <Sidebar />
                <div className="ml-64 lg:ml-64">
                  {children}
                </div>
              </>
            )}
          </DynamicVantaBackground>
        </body>
    </html>
  );
}

